language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DOCKER_COMPOSE_VERSION=1.24.1
services:
  - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - /usr/local/bin/docker-compose pull
install:
  - pip install -r requirements.txt
  - /usr/local/bin/docker-compose up -d
# command to run tests
before_script:
  # Startup the app
  - bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080)" != "200" ]]; do sleep 5; done'
script:
  - nosetests tests
