version: '3'    
services:    
  hyperplan-server:    
    image:  hyperplan/server:latest
    ports:    
     - "8080:8080"    
    restart: always    
    environment:
      - APP_SECRET=replacewithrandomsecret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_health"]
      interval: 10s 
      timeout: 5s
      retries: 5
  postgres:    
    image: "postgres:latest"    
    environment:    
     - POSTGRES_PASSWORD=postgres

